---
# tasks file for remove_domain_computer_account
- debug:
    msg: "{{ hostvars }}"

- name: Remove computer account from domain
  win_domain_computer:
    name: "{{ decomm_domain_computer_account }}"
    state: absent
    delegate_to: ip-172-31-15-130.ec2.internal
